create table customers
(
    id            bigint generated by default as identity,
    customer_name varchar(255),
    level         integer,
    primary key (id)
);


create table orders
(
    id            bigint generated by default as identity,
    order_date    date,
    delivery_date date,
    status        varchar(255),
    customer_id   bigint,
    primary key (id)
);

create table products
(
    id       bigint generated by default as identity,
    name     varchar(255),
    category varchar(255),
    price    double,
    primary key (id)
);

create table orders_products_rel
(
    order_id   bigint not null,
    product_id bigint not null,
    primary key (order_id, product_id)
);

alter table orders_products_rel
    add constraint FK_orders_products_rel_products
        foreign key (product_id) references products;

alter table orders_products_rel
    add constraint FK_orders_products_rel_purchase_orders
        foreign key (order_id) references orders;

alter table orders
    add constraint FK_customers
        foreign key (customer_id) references customers;
